# Generated by Django 4.2.1 on 2023-06-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/blog.jpg', null=True, upload_to='images'),
        ),
    ]
