# Generated by Django 4.2.1 on 2023-07-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('노출', '노출'), ('비노출', '비노출')], default='published', max_length=10),
        ),
    ]
