# Generated by Django 4.2.1 on 2023-07-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10),
        ),
    ]
