# Generated by Django 4.2.1 on 2023-07-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_image_alter_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created'], 'verbose_name': '세금뉴스'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='/blog.jpg', null=True, upload_to='images', verbose_name='이미지'),
        ),
    ]
