# Generated by Django 4.2.1 on 2023-05-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date'], 'verbose_name': '포스트'},
        ),
    ]
