# Generated by Django 4.2.1 on 2023-06-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글'},
        ),
    ]
