# Generated by Django 4.2.1 on 2023-06-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
