# Generated by Django 4.2.1 on 2023-06-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_comment_name_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
