# Generated by Django 4.2.1 on 2023-06-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('신규', '신규'), ('완료', '완료'), ('진행중', '진행중'), ('보류', '보류')], default='신규', max_length=10),
        ),
    ]
