# Generated by Django 4.2.1 on 2023-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_post_number_post_subject_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dbcode',
            field=models.CharField(choices=[('db01', 'db01'), ('db02', 'db02'), ('db03', 'db03')], default='', max_length=10),
        ),
    ]
