# Generated by Django 4.2.1 on 2023-07-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_post_dbcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dbcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
