# Generated by Django 4.2.1 on 2023-07-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_post_dbcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dbcode02',
            field=models.CharField(default='', max_length=10),
        ),
    ]
