# Generated by Django 4.2.1 on 2023-07-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_post_dbcode02'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(default='as01', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='dbcode',
            field=models.CharField(default='db01', max_length=10),
        ),
    ]
