# Generated by Django 4.2.1 on 2023-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_post_code_alter_post_dbcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='terms_confirmed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='이름(상호)'),
        ),
    ]
