# Generated by Django 4.2.1 on 2023-07-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_post_terms_confirmed_alter_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='terms_confirmed',
            field=models.CharField(choices=[('선택', '선택'), ('동의함', '동의함')], max_length=10, null=True, verbose_name='개인정보 수집 및 이용에 동의합니다.'),
        ),
    ]
