# Generated by Django 4.2.1 on 2023-07-10 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_post_title_post_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
    ]
